### ISSUE TITLE
Feature request: new pod select for rolled deployments

### ISSUE THREAD

**Issue by Tarick** [knight42/krelay#1]
When using the deployment as the target, the agent doesn't see that the pod was deleted and the next connection to the port-forwarded port still tries to forward to the old pod. Once "kubectl relay" is restarted this is fixed, but I'd really like not to do that.

**Comment by Tarick** [comment]
@knight42 unfortunately I'm connecting to the "debug" port, which is not exposed via Service. Creating the Service only to support such usecase is not the best user experience, I thought that krelay could help me here, but I set the expectations too high.
Either way, if you choose to implement it, this will greatly add to krelay value. During my development workflow I need to update Deployment frequently and restarting the port-forwarding constantly is really annoying.

**Comment by knight42** [comment]
>  Creating the Service only to support such usecase is not the best user experience

@Tarick I also consider this to be a valuable feature, but it might take some time to work it out and I cannot guarantee how long it will take. Before this is actually implemented, you could create a "debug" service or add the "debug" port to your service as a workaround.

**Comment by knight42** [comment]
@Tarick Hi! This feature has already been implemented, please upgrade krelay to v0.0.2(`kubectl krew upgrade krew`) to give it a try!

**Comment by Tarick** [comment]
Thanks, @knight42 , everything works perfectly! Nice work!
