### ISSUE TITLE
--server.namespace fails unless default namespace is used

### ISSUE THREAD

**Issue by sergeykad** [knight42/krelay#17]
If I don't execute `kubectl config set-context --current --namespace="$ENVIRONMENT"` before creating a relay, an error occurs. However, when the default namespace is set, the process works correctly.

The relay command is `kubectl relay --server.namespace "$ENVIRONMENT" "service/$service" "$ports" --address 0.0.0.0 `

The error is `Error: ensure krelay-server: create krelay-server pod: pods is forbidden: User "foobar" cannot create resource "pods" in API group "" in the namespace "default"`

**Comment by knight42** [comment]
The error message indicates that you are not allowed to create pod in the "default" namespace. 

`krelay` will create the `krelay-server` pod in the namespace specified by the flag `--server.namespace`. If the value of `$ENVIRONMENT` was not `default`, I have no clue why such error occurred. 

@sergeykad Could you post the output of `kubectl relay --server.namespace "$ENVIRONMENT" "service/$service" "$ports" --address 0.0.0.0 -v=7` to help us see what happens?

**Comment by sergeykad** [comment]
The error I mentioned is the only output I am getting: `Error: ensure krelay-server: create krelay-server pod: pods is forbidden: User "foobar" cannot create resource "pods" in API group "" in the namespace "default"`

The value of the `$ENVIRONMENT` was not `default` but a name of an actual namespace. The user has permission to the   `$ENVIRONMENT` namespace but not to `default`

**Comment by knight42** [comment]
So the actual error is
> Error: services "dal-entities" is forbidden: User "foobar" cannot get resource "services" in API group "" in the namespace "default"

That's caused by how `krelay` works, since you are `port-forward`ing to a `Service` in "default" namespace, `krelay` needs to know the `clusterIP` by GET the target `Service`. If you are not allowed to do this, you could try the following:

```
krelay --server.namespace "$ENVIRONMENT" ip/<your service cluster ip> "$ports" --address 0.0.0.0
```

**Comment by sergeykad** [comment]
I see. Is not it possible to select cluster by name?
