### ISSUE TITLE
Clean up orphan pods (self destruct idle pods)

### ISSUE THREAD

**Issue by elvis-cai** [knight42/krelay#24]
Hi, we are using krelay to forward ip address which is accessible to the pod only, and forward to our laptop, it works perfectly, however, when the season for`kubectl krelay` is not cleaned up properly, for example close the laptop to put it to sleep for a few minutes..  then reopen the laptop, the network will be reconnected, we just find `krelay-server` is still running and we need manually clean them up, just curious if there's any plan to support to self destruct `krelay-server` after idle for some time, thanks.

**Comment by knight42** [comment]
Hi @elvis-cai , thanks for reaching out.

If `krelay` is terminated by Ctrl-C, it will attemp to remove the server pod on exit: 
* https://github.com/knight42/krelay/blob/c942acdabc4a74e3b64433aa548814c37614d905/cmd/client/main.go#L216-L218
* https://github.com/knight42/krelay/blob/c942acdabc4a74e3b64433aa548814c37614d905/cmd/client/main.go#L136-L141

> if there's any plan to support to self destruct krelay-server after idle for some time, thanks.

It is a bit tricky to tell if a `krelay-server` is idle and whether a corresponding `krelay` client is going to establish a connection, let alone there is no self destruction mechanism for pods in k8s(an approximate solution would be creating a job for the pod). Therefore I currently have no plan to implement such thing in `krelay`. If you are sure the existing `krelay-server` pods are dangling, you could remove them by `kubectl delete -A pod -lapp=krelay-server`.

**Comment by elvis-cai** [comment]
thanks @knight42 for the details, understood the situation, will spin up the cronjob regularly to clean the zombie pods 👍
