### ISSUE TITLE
Add nodeSelector and tolerations flags

### ISSUE THREAD

**Issue by mgss-cc** [knight42/krelay#47]
Hi, 

It would be great if we are able to pass nodeSelector and tolerations as flags to the krelay command. Sometimes in multitenancy, we want pods to be deployed on certain nodes.

**Comment by knight42** [comment]
I plan to add a flag, say --custom, so that users are able to specify the path to a JSON or YAML file containing a partial pod object to customize the relay agent pod.

Let's take your use case as an example, you can do something like this:

```
$ cat custom-pod.yaml
spec:
  tolerations:
    - ...
  nodeSelector:
    k: v

$ kubectl relay --custom custom-pod.yaml ...
```

**Comment by knight42** [comment]
@mgss-cc Hi, with krelay 0.1.1, you could customize the krelay-server pod by the `--patch`/`--patch-file` flag. For instance:

$ kubectl relay --patch-file custom-pod.yaml ...
