### ISSUE TITLE
no docker release for v0.0.10

### ISSUE THREAD

**Issue by grzn** [knight42/krelay#50]
hi

there's an image only for v0.0.3
can you please release v0.0.10?
thanks

**Comment by knight42** [comment]
Hi @grzn , the release of [krelay-server](https://github.com/knight42/krelay/pkgs/container/krelay-server) is separated from [krelay](https://github.com/knight42/krelay/releases) itself. I would only push a new image if there is server side changes.

BTW if you need to customize the krelay-server, please refer to https://github.com/knight42/krelay/blob/main/manifests/Dockerfile-server and build one that satifies your needs.
