### ISSUE TITLE
Lost connection to krelay-server pod

### ISSUE THREAD

**Issue by jogomu** [knight42/krelay#9]
Hello, whether using port-forward or your krew plugin, I get a similar problem, only it seems to be slightly worse (more frequent) with port-forward.

There appears to be no logging from your pod component that would shed light on this.

The pod container is publishing data very quickly on the TCP socket initiated by my local client.  I wonder if some buffer somewhere is getting overwhelmed?

Command was kubectl relay --kubeconfig=... --address 0.0.0.0 pod/$POD 23456:23456

For testing try sending multiple gigabytes as quickly as you can from pod back to client.
EDIT: and try sending a stop signal to the client (ctrl+z on max/linux) so that it isn't draining the socket... problem appears faster

I0810 18:07:48.590131   73054 tcp.go:22] "Handling tcp connection" reqID="70e80503-0e95-48e9-a466-2624ce13ddb8" dstAddr="10.244.9.32:23456" localAddr="127.0.0.1:23456" clientAddr="127.0.0.1:57880"
I0810 23:07:48.677016       1 main.go:59] "Start proxy tcp request" reqID="70e80503-0e95-48e9-a466-2624ce13ddb8" dstAddr="10.244.9.32:23456"
I0810 23:20:28.096485       1 tcp.go:48] "Client close connection" reqID="70e80503-0e95-48e9-a466-2624ce13ddb8"
I0810 23:20:28.096895       1 tcp.go:66] "ProxyTCP exit" reqID="70e80503-0e95-48e9-a466-2624ce13ddb8"
I0810 18:20:48.518316   73054 main.go:182] "Lost connection to krelay-server pod"
I0810 18:20:48.518368   73054 utils.go:96] "Removing krelay-server pod" pod="krelay-server-8h7mk"

**Comment by knight42** [comment]
Sorry for the late response, I guess this problem is caused by an underlying networking issue, and might be out of the scope of this kubectl plugin, https://github.com/kubernetes/kubernetes/issues might be a better place to post your problem there.

**Comment by knight42** [comment]
Close for now. Please feel free to reopen if you think this is still a `krelay` issue.
